class Country {
  final int? id;
  final String name;
  final String capital;
  final String region;
  final int population;
  final String flagUrl;
  final List<String> languages;

  Country({
    this.id,
    required this.name,
    required this.capital,
    required this.region,
    required this.population,
    required this.flagUrl,
    required this.languages,
  });

  // Factory constructor to create a Country from a JSON map
  factory Country.fromJson(Map<String, dynamic> json) {
    return Country(
      name: json["name"]?["common"] ?? "Unknown Country",
      capital: (json["capital"]?.isNotEmpty ?? false) ? json["capital"][0] : "No Capital",
      region: json["region"] ?? "No Region",
      population: json["population"] ?? 0,
      flagUrl: json["flags"]?["png"] ?? "",
      languages: json["languages"] != null
          ? (json["languages"] as Map<String, dynamic>).values.toList().cast<String>()
          : [],
    );
  }

    factory Country.fromMap(Map<String, dynamic> map) {
    return Country(
      id: map['id'], // The id will be auto-generated by SQLite
      name: map['name'],
      capital: map['capital'],
      region: map['region'],
      population: map['population'],
      languages: map['languages'],
      flagUrl: map['flag'],
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'name': name,
      'capital': capital,
      'region': region,
      'flagUrl': flagUrl,
      'languages': languages,
      'population':population
    };
  }
}
  
